apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80        # Port exposed by the service
    targetPort: 80  # Port on the pod
    nodePort: 30080 # Port on each node (30000-32767 range)
    protocol: TCP
    name: http
  selector:
    app: nginx

