# ============================================
# Service Account Example - TEACHING GUIDE
# ============================================
# Service Accounts provide identity for pods running in Kubernetes.
# Think of it like an employee badge - it identifies who the pod is.
# Without a Service Account, pods use the "default" one which has NO permissions.
#
# Key Concepts:
# - Service Accounts are namespace-scoped (each namespace has its own)
# - Every namespace automatically gets a "default" service account
# - Pods need Service Accounts to authenticate to Kubernetes API
# - Service Accounts are used with RBAC (Roles/RoleBindings) for permissions
#
# To apply: kubectl apply -f service-account.yaml
# To view: kubectl get serviceaccounts (or kubectl get sa)
# To check details: kubectl describe sa my-service-account
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account       # This name is used when referencing in pods
                                  # In pod spec: serviceAccountName: my-service-account
                                  # Also used in RoleBindings as the subject
                                  # Must be unique within the namespace
  namespace: default             # Service Accounts are namespace-scoped
                                  # Each namespace has its own set of service accounts
                                  # If omitted, uses "default" namespace
  labels:
    app: myapp                   # Labels help organize and select service accounts
                                  # Optional but recommended for better management
spec:
  # ============================================
  # Image Pull Secrets
  # ============================================
  # When your container images are in PRIVATE registries (Docker Hub private,
  # AWS ECR, Google Container Registry, Azure Container Registry), you need
  # credentials to pull them. Image pull secrets store these credentials.
  #
  # How it works:
  # 1. Create a secret with registry credentials
  # 2. Reference it here in the service account
  # 3. All pods using this service account can pull from private registry
  #
  # Common mistake: Secret doesn't exist - pods will fail with ImagePullBackOff
  # ============================================
  imagePullSecrets:
  - name: registry-secret         # Name of the secret containing registry credentials
                                  # This secret MUST exist in the same namespace
                                  # Secret type should be: kubernetes.io/dockerconfigjson
                                  # If secret doesn't exist, image pulls will fail
  
  # ============================================
  # Automount Service Account Token
  # ============================================
  # Kubernetes automatically mounts a token file in every pod that uses this
  # service account. This token is used to authenticate to the Kubernetes API.
  #
  # Token location in pod:
  # /var/run/secrets/kubernetes.io/serviceaccount/token
  #
  # When to set false:
  # - Pod doesn't need to access Kubernetes API
  # - Security: Reduce attack surface
  # - Pod only needs to pull images (no API calls)
  #
  # Default: true (most pods need API access for service discovery, etc.)
  # ============================================
  automountServiceAccountToken: true  # true = mount token (default)
                                      # false = don't mount token
                                      # Token is used for API authentication
                                      # Pods can use this token to call Kubernetes API
  
  # ============================================
  # TEACHING POINTS TO EXPLAIN:
  # ============================================
  # 1. Default Service Account:
  #    - Every namespace has a "default" service account
  #    - Created automatically by Kubernetes
  #    - Usually has NO permissions (empty)
  #    - Pods without serviceAccountName use "default"
  #
  # 2. Why Create Custom Service Accounts:
  #    - Default SA has no permissions
  #    - Need custom SA + RBAC for pod permissions
  #    - Different apps need different permissions
  #    - Better security (principle of least privilege)
  #
  # 3. Common Workflow:
  #    Step 1: Create Service Account (this file)
  #    Step 2: Create Role (defines permissions)
  #    Step 3: Create RoleBinding (grants role to service account)
  #    Step 4: Use in pod: serviceAccountName: my-service-account
  #
  # 4. Testing:
  #    - kubectl get sa (see all service accounts)
  #    - kubectl describe sa my-service-account (see details)
  #    - Check if secret exists: kubectl get secret registry-secret
  # ============================================

