apiVersion: v1
kind: Pod
metadata:
  name: nginx-ssd
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
  nodeSelector:
    disktype: ssd  # Pod will only run on nodes with this label
    # Add more labels for AND logic
    # environment: production

