# ============================================
# Basic Secret Example
# ============================================
# This Secret stores sensitive data like passwords
# and API keys. Data is base64 encoded (NOT encrypted).
#
# ⚠️ SECURITY WARNING:
# - Secrets are base64 encoded, NOT encrypted
# - Anyone with cluster access can decode them
# - Always use RBAC to restrict access
# - Never commit secrets to version control
#
# What this demonstrates:
# 1. Using stringData (plain text, auto-encoded)
# 2. Using data (pre-encoded base64)
# 3. Opaque secret type (generic user-defined).
#
# To apply: kubectl apply -f basic-secret.yaml
# To view: kubectl get secret app-secret -o yaml
# To decode: kubectl get secret app-secret -o jsonpath='{.data.password}' | base64 -d
# ============================================

apiVersion: v1
kind: VaultSecret
metadata:
  name: app-secret # Secret name (used to reference in pods)
type:
  Opaque # Generic user-defined secret (default type)
  # Other types: kubernetes.io/tls, kubernetes.io/dockerconfigjson

# ============================================
# stringData Section
# ============================================
# Plain text values that are automatically
# base64 encoded by Kubernetes.
#
# Use this for:
# - Easier to read and write
# - Values in plain text (be careful!)
# - Development and learning
#
# ⚠️ Note: Values are visible in YAML file!
# For production, consider using data section
# with pre-encoded values or external secret managers.
# ============================================
stringData: # Plain text (automatically base64 encoded)
  username: admin
  password: secret123
  api_key: abc123xyz789

# ============================================
# data Section
# ============================================
# Pre-encoded base64 values.
#
# To encode a value:
#   echo -n 'your-value' | base64
#
# Use this for:
# - Hiding values in YAML (still not secure!)
# - Values already encoded
# - Slightly better than plain text in files
#
# ⚠️ Remember: Base64 is encoding, NOT encryption!
# Anyone can decode: echo 'c3VwZXJzZWNyZXQ=' | base64 -d
# ============================================
data: # Base64 encoded values
  # To create: echo -n 'value' | base64
  database_password: c3VwZXJzZWNyZXQ= # "supersecret" in base64


  # ============================================
  # How to Use This Secret:
  # ============================================
  # Method 1: As Environment Variables
  #   env:
  #   - name: DB_PASSWORD
  #     valueFrom:
  #       secretKeyRef:
  #         name: app-secret
  #         key: password
  #
  # Method 2: As Volume (More Secure)
  #   volumes:
  #   - name: secret-volume
  #     secret:
  #       secretName: app-secret
  #   volumeMounts:
  #   - name: secret-volume
  #     mountPath: /etc/secrets
  #     readOnly: true
  #
  # Method 3: For Docker Registry
  #   imagePullSecrets:
  #   - name: app-secret
  # ============================================
